version: "3"
networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    container_name: mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ${MYSQL_HOST_DATA_PATH}:${MYSQL_CONTAINER_DATA_PATH}
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      backend:
        ipv4_address: 172.20.0.4

  redis:
    build: ./redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/log/redis.log:/var/log/redis/redis-server.log
      - ${REDIS_HOST_DATA_PATH}:${REDIS_CONTAINER_DATA_PATH}
    networks: 
      backend:
        ipv4_address: 172.20.0.5

  php-fpm:
    build:
      context: ./php
      args:
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_XDEBUG=${PHP_INSTALL_XDEBUG}
        - INSTALL_REDIS=${PHP_INSTALL_REDIS}
        - INSTALL_JIEBA=${PHP_INSTALL_JIEBA}
        - INSTALL_SWOOLE=${PHP_INSTALL_SWOOLE}
        - INSTALL_PYTHON2=${PHP_INSTALL_PYTHON2}
        - INSTALL_PYTHON3=${PHP_INSTALL_PYTHON3}
        - INSTALL_PYTHON_PACK=${PHP_INSTALL_PYTHON_PACK}
        - INSTALL_IMAGIC=${PHP_INSTALL_IMAGIC}
        - INSTALL_LATEX=${PHP_INSTALL_LATEX}
    container_name: php-fpm
    working_dir: ${CONTAINER_PROJECT_PATH}
    user: ${USER_ID}:${USER_ID}
    ports:
      - "9000:9000"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    links:
      - "mysql"
      - "redis"
    depends_on:
      - "mysql"
      - "redis"
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/log/php-fpm.log:/var/log/php-fpm.log
      - ${HOST_PROJECT_PATH}:${CONTAINER_PROJECT_PATH}
      - ./php/log/xdebug.log:/var/log/xdebug.log
    networks: 
      backend:
        ipv4_address: 172.20.0.7

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php-fpm"
    depends_on:
      - "php-fpm"
    volumes:
      - ${HOST_PROJECT_PATH}:${CONTAINER_PROJECT_PATH}
      - ./nginx/site-enabled/:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/:/etc/nginx/ssl/
      - ./nginx/log/:/nginx/log
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks: 
      backend:
        ipv4_address: 172.20.0.3

  workspace:
    build:
      context: ./workspace
      args:
        - USER_ID=${USER_ID}
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_GIT=${WORKSPACE_INSTALL_GIT}
        - INSTALL_VIM=${WORKSPACE_INSTALL_VIM}
        - INSTALL_NETTOOLS=${WORKSPACE_INSTALL_NETTOOLS}
        - INSTALL_COMPOSER=${WORKSPACE_INSTALL_COMPOSER}
        - INSTALL_PS_WATCHER=${WORKSPACE_INSTALL_PS_WATCHER}
        - INSTALL_MONGO=${WORKSPACE_INSTALL_MONGO}
    container_name: workspace
    user: ${USER_ID}:${USER_ID}
    working_dir: ${CONTAINER_PROJECT_PATH}
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ${HOST_PROJECT_PATH}:${CONTAINER_PROJECT_PATH}
      - ./cache/composer-cache/:/home/docker/.composer/
    tty: true
    links:
      - mysql
      - redis
    networks:
      backend:
        ipv4_address: 172.20.0.8

  phpunit:
    build:
      context: ./phpunit
      args:
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_LATEX=${PHP_INSTALL_LATEX}
    container_name: phpunit
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - /develop:/develop
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/bin/docker
    tty: true
    links:
      - mysql
      - redis
    networks:
      backend:
        ipv4_address: 172.20.0.9

  node:
    build:
      context: ./node
      args:
        - NODE_VERSION=${NODE_VERSION}
    container_name: node
    user: ${USER_ID}:${USER_ID}
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
      - "www.auth.localhost:172.20.0.3"
    ports:
      - "8000-8010:8000-8010"
    volumes:
      - /develop:/develop
      - ./cache/npm-cache/:/home/node/.npm/
    links: 
      - java
    tty: true
    networks: 
      backend:
        ipv4_address: 172.20.0.2

  java:
    build:
      context: ./java
      args:
        - JDK_VERSION=${JDK_VERSION}
        - USER_ID=${USER_ID}
    container_name: java
    user: ${USER_ID}:${USER_ID}
    volumes:
      - /develop:/develop
      - ${HOST_MAVEN_PATH}:/usr/local/maven
      - ${HOST_GRADLE_PATH}:/usr/local/gradle
      - ${HOST_JAVAFX_PATH}:/usr/local/lib/javafx
      - ./cache/gradle-cache/:/home/docker/.gradle/
      - ./cache/maven-cache/:/home/docker/.m2/
      - ./cache/javafx-cache/:/home/docker/.openjfx/
    extra_hosts:
      - "www.auth.localhost:172.20.0.3"
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "8080:8080"
    tty: true
    links:
      - mysql
      - redis
    networks:
      backend:
        ipv4_address: 172.20.0.6