services:
  mysql:
    build:
      context: ../containers/services/mysql
      dockerfile: ./Dockerfile
      args:
        - MYSQL_IMAGE=${MYSQL_IMAGE}
        - MYSQL_VERSION=${MYSQL_VERSION}
    container_name: mysql
    image: docker-mysql:${MYSQL_VERSION}
    mem_limit: ${MYSQL_MEM_LIMIT:-2g}
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ${HOST_PROJECT_PATH}:${CONTAINER_PROJECT_PATH}
      - ${MYSQL_HOST_DATA_PATH}:${MYSQL_CONTAINER_DATA_PATH}
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      - ../containers/services/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    # 降低mysql容器的内存占用
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677
    ports:
      - "${MYSQL_PORT}:3306"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      backend:
        ipv4_address: 172.20.0.4

  postgres:
    build:
      context: ../containers/services/postgres
      dockerfile: ./Dockerfile
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    container_name: postgres
    image: docker-postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TIMEZONE}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_HOST_DATA_PATH}:/var/lib/postgresql
      - ../containers/services/postgres/log:/var/log/postgresql
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      backend:
        ipv4_address: 172.20.0.6

  redis:
    build:
      context: ../containers/services/redis
      dockerfile: ./Dockerfile
      args:
        - REDIS_VERSION=${REDIS_VERSION}
    container_name: redis
    image: docker-redis:${REDIS_VERSION}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ../containers/services/redis/log/redis.log:/var/log/redis/redis-server.log
      - ${REDIS_HOST_DATA_PATH}:${REDIS_CONTAINER_DATA_PATH}
      - ../containers/services/redis/redis.conf:/usr/local/etc/redis/redis.conf
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      backend:
        ipv4_address: 172.20.0.5

  mongo:
    build:
      context: ../containers/services/mongo
      dockerfile: Dockerfile
      args:
        - MONGO_VERSION=${MONGO_VERSION}
    container_name: mongo
    image: docker-mongo:${MONGO_VERSION}
    user: ${HOST_UID}:${HOST_GID}
    environment:
      - MONGO_DATA_DIR=${MONGO_CONTAINER_DATA_DIR}
      - MONGO_LOG_DIR=${MONGO_CONTAINER_LOG_DIR}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ${HOST_PROJECT_PATH}:${CONTAINER_PROJECT_PATH}
      - ${MONGO_HOST_DATA_DIR}:${MONGO_CONTAINER_DATA_DIR}
      - ${MONGO_HOST_LOG_DIR}:${MONGO_CONTAINER_LOG_DIR}
    ports:
      - "${MONGO_PORT}:27017"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      backend:
        ipv4_address: 172.20.0.11

  nginx:
    build:
      context: ../containers/services/nginx
      dockerfile: ./Dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION}
        - PHP_FPM_PORT=${PHP_FPM_PORT}
        - USER_ID=${HOST_UID}
    container_name: nginx
    image: docker-nginx:${NGINX_VERSION}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${HOST_PROJECT_PATH}:${CONTAINER_PROJECT_PATH}
      - ../containers/services/nginx/site-enabled:/etc/nginx/conf.d
      - ../containers/services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../containers/services/nginx/ssl:/etc/nginx/ssl
      - ../containers/services/nginx/log:/nginx/log
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      backend:
        ipv4_address: 172.20.0.3
